version: "3.8"

networks:
    laravel:
        driver: bridge

services:
    nginx:
        container_name: "nginx"
        build:
            context: ./docker-repo/nginx
            dockerfile: nginx.dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        ports:
            - "${FORWARD_NGINX_PORT:-80}:80"
        volumes:
            - .:/var/www/html:delegated
        depends_on:
            - php
            - redis
            - mysql
        networks:
            - laravel

    mysql:
        container_name: "mysql"
        image: mariadb:10.6
        restart: unless-stopped
        tty: true
        ports:
            - "${FORWARD_MYSQL_PORT:-3306}:3306"
        volumes:
            - ./docker-repo/mysql/mysql:/var/lib/mysql:delegated
            - ./docker-repo/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: "${DB_DATABASE:-default_db}"
            MYSQL_USER: "${DB_USERNAME:-default_user}"
            MYSQL_PASSWORD: "${DB_PASSWORD:-default_password}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-default_password}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            TZ: "${TZ:-Asia/Tehran}"
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-p${DB_PASSWORD:-default_password}",
                ]
            retries: 3
            timeout: 5s
        networks:
            - laravel

    php:
        container_name: "php"
        build:
            context: ./docker-repo/php
            dockerfile: php.dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        ports:
            - "${FORWARD_PHP_PORT:-9000}:9000"
        volumes:
            - .:/var/www/html:delegated
            - ./docker-repo/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - laravel

    phpmyadmin:
        container_name: "phpmyadmin"
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "${FORWARD_PHPMYADMIN_PORT:-8081}:80"
        environment:
            PMA_HOST: mysql
            PMA_PASSWORD: "${DB_PASSWORD:-default_password}"
            UPLOAD_LIMIT: 64M
        depends_on:
            - mysql
        networks:
            - laravel

    redis:
        container_name: "redis"
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        networks:
            - laravel

    composer:
        container_name: "composer"
        build:
            context: ./docker-repo/php
            dockerfile: php.dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        volumes:
            - .:/var/www/html
        depends_on:
            - php
        entrypoint: ["composer", "--ignore-platform-reqs"]
        networks:
            - laravel

    npm:
        container_name: "npm"
        image: node:current-alpine
        volumes:
            - .:/var/www/html
        ports:
            - "${FORWARD_NPM_PORT:-3000}:3000"
        working_dir: /var/www/html
        entrypoint: ["npm"]
        networks:
            - laravel

    artisan:
        container_name: "artisan"
        build:
            context: ./docker-repo/php
            dockerfile: php.dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        volumes:
            - .:/var/www/html:delegated
        depends_on:
            - mysql
        entrypoint: ["php", "/var/www/html/artisan"]
        networks:
            - laravel
